### ISSUE TITLE
CodeGen: Wrongfully picked up qubit

### ISSUE THREAD

**Issue by ystade** [UCLA-VAST/DPQA#2]
I am trying to get DPQA running for a couple of benchmark circuits. During this process, I experienced some unexpected behaviour. The error occurred during the execution of the following script from the root directory of the repository:

```python
from solve import DPQA
from animation import CodeGen
import json

dpqa = DPQA("my_graph", dir="./results/smt/")
dpqa.setArchitecture([16, 16, 16, 16])
graph = [[5, 6], [5, 6], [4, 6], [3, 6], [2, 6], [1, 6], [4, 6], [3, 6], [2, 6],
         [1, 6], [4, 5], [3, 5], [2, 5], [1, 5], [0, 6], [4, 5], [3, 5], [2, 5],
         [1, 5], [0, 6], [3, 4], [2, 4], [1, 4], [0, 5], [3, 4], [2, 4], [1, 4],
         [0, 5], [2, 3], [1, 3], [0, 4], [2, 3], [1, 3], [0, 4], [1, 2], [0, 3],
         [2, 4], [1, 2], [0, 3], [2, 4], [0, 2], [2, 4], [0, 2], [0, 1], [1, 5],
         [0, 1], [1, 5], [1, 5], [0, 6], [0, 6], [0, 6]]
dpqa.setProgram(graph)
dpqa.hybrid_strategy()
dpqa.solve(save_file=True)

with open("./results/smt/my_graph.json") as f:
    data = json.load(f)
codegen = CodeGen("./results/smt/my_graph.json", no_transfer=data['no_transfer'], dir="./results/code/")
```

Executing this yields the error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 1307, in __init__
    program = self.builder(no_transfer)
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 1438, in builder
    self.builder_reload(s, cols, rows, qubits, program)
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 1762, in builder_reload
    reloadRow_obj.generate_row_activate(
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 970, in generate_row_activate
    Activate(s=self.stage,
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 524, in __init__
    self.verify(
  File "/Users/yannick/Documents/TUM/CDA/Research/projects/mqt-qmap/extern/dpqa/animation.py", line 665, in verify
    raise ValueError(
ValueError: Reload_12:ReloadRow_7:Activate: q 5 wrongfully picked up by col 3 row 5 at x=60 y=100.
```

I appreciate any help with this issue.

FYI: The issue was observed on a MacBook Pro with an M3 chip and Sonoma 14.3.1 installed. The Python version used was 3.10.10.

**Comment by qu-tan-um** [comment]
Hi, thanks for the interest in this project. Somehow GitHub didn't notice me when you submitted. I just saw it today. 

I tried to reproduce the bug, but there's no such error on my computer. Please take a look at this branch: https://github.com/UCLA-VAST/DPQA/tree/issue2

I copied your script as `issue2.py`, and in `results/` there are 3 new files as results of running the script.

**Comment by qu-tan-um** [comment]
My machine is quite different from yours. It's a Linux server with x86 CPU. However, that shouldn't be an issue since we're just using Python. Out of curiosity, what version of `z3-solver` are you using?

**Comment by ystade** [comment]
Currently, I use `z3-solver==4.13.0.0`. However, when I reported the issue, the version was an older one that I do not recall anymore, but probably `4.12.6.0` or `4.12.5.0`.

In the meantime, I figured out that the issue does not occur with the default settings. We modified the parameters in the `animation.py` file as follows and only then I can reproduce the error.

```diff
diff --git a/animation.py b/animation.py
index 417aa1e..0548604 100644
--- a/animation.py
+++ b/animation.py
@@ -9,12 +9,12 @@ from abc import ABC, abstractmethod
 
 
 # physics constants
-R_B = 6  # rydberg range
-AOD_SEP = 2  # min AOD separation
-RYD_SEP = 15  # sufficient distance to avoid Rydberg
+R_B = 2  # rydberg range
+AOD_SEP = 1  # min AOD separation
+RYD_SEP = 10  # sufficient distance to avoid Rydberg
 SITE_SLMS = 2  # number of SLMs in a site
 SLM_SEP = AOD_SEP  # separation of SLMs inside a site
-SITE_WIDTH = 4  # total width of SLMs in a site
+SITE_WIDTH = 2  # total width of SLMs in a site
 X_SITE_SEP = RYD_SEP + SITE_WIDTH  # separation of sites in X direction
 Y_SITE_SEP = RYD_SEP  # separation of sites in Y direction
 ```

**Comment by qu-tan-um** [comment]
That makes sense. I haven't really tested the software with different parameters like you tried. I need to look into this issue, but it will take some time. 

Out of curiosity, why do you want to change these numbers?

**Comment by ystade** [comment]
The reason for the change is that with these settings the outcome is more comparable to the results that we compare it to, i.e., mapping of circuits to the zoned architecture described in the paper from Bluvstein et al. [^1].

[^1]: D. Bluvstein et al., ‘Logical quantum processor based on reconfigurable atom arrays’, Nature, Dec. 2023, doi: [10.1038/s41586-023-06927-3](https://doi.org/10.1038/s41586-023-06927-3).

**Comment by qu-tan-um** [comment]
We have fixed this issue with [the recent commit on main branch](https://github.com/UCLA-VAST/DPQA/commit/600df66af4136ccdab88b49c28e1771ef2a8cbe9). We have also reduced some parameters in the beginning because our code can't adapt to some settings. For your set of parameters, it should work. Let us know if there are any other issues. Thanks very much!
